using EventStore.Client;
using Kurrent.Client.Core.Serialization;

namespace Kurrent.Client.Tests.Core.Serialization;

public class MessageSerializerTests {
	[Fact]
	public void Serialize_WithValidMessage_ReturnsEventData() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var data      = new UserRegistered("user-123", "user@random-email.com");
		var metadata  = new TestMetadata();
		var messageId = Uuid.NewUuid();
		var message   = Message.From(data, metadata, messageId);

		var context = new MessageSerializationContext("user-123", ContentType.Json);

		// When
		var eventData = serializer.Serialize(message, context);

		// Then
		Assert.Equal(messageId, eventData.EventId);
		Assert.Equal("UserRegistered", eventData.Type);
		Assert.NotEmpty(eventData.Data.Span.ToArray());
		Assert.NotEmpty(eventData.Metadata.Span.ToArray());
		Assert.Equal(ContentType.Json.ToMessageContentType(), eventData.ContentType);
	}

	[Fact]
	public void Serialize_WithAutoGeneratedId_GeneratesNewId() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var data    = new UserRegistered("user-123", "user@random-email.com");
		var message = Message.From(data); // No ID provided

		var context = new MessageSerializationContext("user-123", ContentType.Json);

		// When
		var eventData = serializer.Serialize(message, context);

		// Then
		Assert.NotEqual(Uuid.Empty, eventData.EventId);
	}

	[Fact]
	public void Serialize_WithoutMetadata_GeneratesEmptyMetadata() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var data    = new UserRegistered("user-123", "user@random-email.com");
		var message = Message.From(data);

		var context = new MessageSerializationContext("user-123", ContentType.Json);

		// When
		var eventData = serializer.Serialize(message, context);

		// Then
		Assert.Empty(eventData.Metadata.Span.ToArray());
	}

	[Fact]
	public void Serialize_WithBinaryContentType_UsesBinarySerializer() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var data    = new UserRegistered("user-123", "user@random-email.com");
		var message = Message.From(data);

		var context = new MessageSerializationContext("user-123", ContentType.Bytes);

		// When
		var eventData = serializer.Serialize(message, context);

		// Then
		Assert.Equal(ContentType.Bytes.ToMessageContentType(), eventData.ContentType);
	}

	[Fact]
	public void SerializeMultiple_WithValidMessages_ReturnsEventDataArray() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var messages = new[] {
			Message.From(new UserRegistered("1", "u1@random-email.com")),
			Message.From(new UserRegistered("2", "u2@random-email.com")),
			Message.From(new UserRegistered("3", "u3@random-email.com"))
		};

		var context = new MessageSerializationContext("user-123", ContentType.Json);

		// When
		var eventDataArray = serializer.Serialize(messages, context);

		// Then
		Assert.Equal(3, eventDataArray.Length);
		Assert.All(eventDataArray, data => Assert.Equal("UserRegistered", data.Type));
	}

	[Fact]
	public void TryDeserialize_WithValidEventRecord_DeserializesSuccessfully() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var testEvent    = new UserRegistered("user-123", "user@random-email.com");
		var testMetadata = new TestMetadata { CorrelationId = "corr-123", UserId = "user-456" };
		var eventId      = Uuid.NewUuid();

		var eventRecord = CreateTestEventRecord("UserRegistered", testEvent, testMetadata, eventId);

		// When
		var success = serializer.TryDeserialize(eventRecord, out var message);

		// Then
		Assert.True(success);
		Assert.NotNull(message);
		Assert.Equal(eventId, message.MessageId);

		var deserializedEvent = Assert.IsType<UserRegistered>(message.Data);
		Assert.Equal("user-123", deserializedEvent.UserId);
		Assert.Equal("user@random-email.com", deserializedEvent.Email);

		var deserializedMetadata = Assert.IsType<TestMetadata>(message.Metadata);
		Assert.Equal("corr-123", deserializedMetadata.CorrelationId);
		Assert.Equal("user-456", deserializedMetadata.UserId);
	}

	[Fact]
	public void TryDeserialize_WithUnknownEventType_ReturnsFalse() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var testEvent   = new UserRegistered("user-123", "user@random-email.com");
		var eventRecord = CreateTestEventRecord("UnknownEventType", testEvent);

		// When
		var success = serializer.TryDeserialize(eventRecord, out var message);

		// Then
		Assert.False(success);
		Assert.Null(message);
	}

	[Fact]
	public void TryDeserialize_WithNullData_ReturnsFalse() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);
		var eventRecord    = CreateTestEventRecord("UserRegistered", null);

		// When
		var success = serializer.TryDeserialize(eventRecord, out var message);

		// Then
		Assert.False(success);
		Assert.Null(message);
	}

	[Fact]
	public void TryDeserialize_WithEmptyMetadata_DeserializesWithNullMetadata() {
		// Given
		var settings       = CreateTestSettings();
		var schemaRegistry = SchemaRegistry.From(settings);
		var serializer     = new MessageSerializer(schemaRegistry);

		var testEvent = new UserRegistered("user-123", "user@random-email.com");
		var eventId   = Uuid.NewUuid();

		var eventRecord = CreateTestEventRecord("UserRegistered", testEvent, null, eventId);

		// When
		var success = serializer.TryDeserialize(eventRecord, out var message);

		// Then
		Assert.True(success);
		Assert.NotNull(message);
		Assert.Equal(eventId, message.MessageId);
		Assert.Null(message.Metadata);

		var deserializedEvent = Assert.IsType<UserRegistered>(message.Data);
		Assert.Equal("user-123", deserializedEvent.UserId);
		Assert.Equal("user@random-email.com", deserializedEvent.Email);
	}

	[Fact]
	public void MessageSerializer_From_CreatesInstanceWithDefaultSettings() {
		// When
		var serializer = MessageSerializer.From();

		// Then - if this doesn't throw, it worked
		Assert.NotNull(serializer);
	}

	[Fact]
	public void MessageSerializer_From_CreatesInstanceWithProvidedSettings() {
		// Given
		var settings = CreateTestSettings();

		// When
		var serializer = MessageSerializer.From(settings);

		// Then - test it works with our settings
		var data    = new UserRegistered("user-123", "user@random-email.com");
		var message = Message.From(data);
		var context = new MessageSerializationContext("user-123", ContentType.Json);

		var eventData = serializer.Serialize(message, context);
		Assert.Equal("UserRegistered", eventData.Type);
	}

	static KurrentClientSerializationSettings CreateTestSettings() {
		var settings = new KurrentClientSerializationSettings();
		settings.RegisterMessageType<UserRegistered>("UserRegistered");
		settings.RegisterMessageType<UserAssignedToRole>("UserAssignedToRole");
		settings.UseMetadataType<TestMetadata>();

		return settings;
	}

	static EventRecord CreateTestEventRecord(
		string eventType, object? data = null, object? metadata = null, Uuid? eventId = null
	) =>
		new(
			Uuid.NewUuid().ToString(),
			eventId ?? Uuid.NewUuid(),
			StreamPosition.FromInt64(0),
			new Position(1, 1),
			new Dictionary<string, string> {
				{ Constants.Metadata.Type, eventType },
				{ Constants.Metadata.Created, DateTime.UtcNow.ToTicksSinceEpoch().ToString() },
				{ Constants.Metadata.ContentType, Constants.Metadata.ContentTypes.ApplicationJson }
			},
			data != null ? _serializer.Serialize(data) : ReadOnlyMemory<byte>.Empty,
			metadata != null ? _serializer.Serialize(metadata) : ReadOnlyMemory<byte>.Empty
		);

	static readonly SystemTextJsonSerializer _serializer = new SystemTextJsonSerializer();

	public record UserRegistered(string UserId, string Email);

	public record UserAssignedToRole(string UserId, string Role);

	public class TestMetadata {
		public string CorrelationId { get; set; } = "correlation-id";
		public string UserId        { get; set; } = "user-id";
	}
}
