name: Test CE

on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        type: string
      docker-image:
        required: false
        type: string
        default: eventstore-ce/eventstoredb-ce

jobs:
  test:
    uses: ./.github/workflows/base.yml
    strategy:      
      fail-fast: false
      matrix:
        framework: [ net6.0, net7.0, net8.0 ]
        os: [ ubuntu-latest ]
        test: [ Streams, PersistentSubscriptions, Operations, UserManagement, ProjectionManagement ]
        configuration: [ release ]
    with:
      docker-tag: ${{ inputs.docker-tag }}
      docker-image: ${{ inputs.docker-image }}
      framework: ${{ matrix.framework }}
      os: ${{ matrix.os }}
      test: ${{ matrix.test }}
      configuration: ${{ matrix.configuration }}
    secrets: 
      CLOUDSMITH_CICD_USER: ${{ secrets.CLOUDSMITH_CICD_USER }}
      CLOUDSMITH_CICD_TOKEN: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}
