name: Dispatch EE

on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: "Docker tag"
        required: true
        type: string
      docker-image:
        description: "Docker image"
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/base.yml
    strategy:
      fail-fast: false
      matrix:
        test: [ Plugins ]
    name: Test EE (${{ inputs.docker-tag }})
    with:
      docker-tag: ${{ inputs.docker-tag }}
      docker-image: ${{ inputs.docker-image }}
      test: ${{ matrix.test }}
    secrets:
      CLOUDSMITH_CICD_USER: ${{ secrets.CLOUDSMITH_CICD_USER }}
      CLOUDSMITH_CICD_TOKEN: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}
