name: Test EE

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        framework: [ net6.0, net7.0, net8.0 ]
        os: [ ubuntu-latest ]
        build: [ Streams, PersistentSubscriptions, Operations, UserManagement, ProjectionManagement ]
        test: [ Plugins ]
        configuration: [ release ]
    runs-on: ${{ matrix.os }}
    name: EventStore.Client.${{ matrix.test }}/${{ matrix.os }}/${{ matrix.framework }}/24.2.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - shell: bash
        run: |
          git fetch --prune --unshallow
      - name: Login to Cloudsmith
        uses: docker/login-action@v3
        with:
          registry: docker.eventstore.com
          username: ${{ secrets.CLOUDSMITH_CICD_USER }}
          password: ${{ secrets.CLOUDSMITH_CICD_TOKEN }}
      - name: Pull EventStore Image
        shell: bash
        run: |
          docker pull docker.eventstore.com/eventstore-ee/eventstoredb-commercial:24.2.0-jammy
      - name: Install dotnet SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Compile
        shell: bash
        run: |
          dotnet build --configuration ${{ matrix.configuration }} --framework ${{ matrix.framework }} src/EventStore.Client.${{ matrix.build }}
      - name: Run Tests
        if: ${{ inputs.docker-registry == '' }}
        shell: bash
        env:
          ES_DOCKER_TAG: 24.2.0-jammy
          ES_DOCKER_REGISTRY: docker.eventstore.com/eventstore-ee/eventstoredb-commercial
        run: |
          sudo ./gencert.sh
          dotnet test --configuration ${{ matrix.configuration }} --blame \
            --logger:"GitHubActions;report-warnings=false" --logger:"console;verbosity=normal" \
            --framework ${{ matrix.framework }} \
            test/EventStore.Client.${{ matrix.test }}.Tests
